### ISSUE TITLE
Still cannot use login

### ISSUE THREAD

**Issue by vmario89** [tulir/mautrix-telegram#300]
Hi,

with latest rc4 i still cannot use login, because a stacktrace is thrown:

Traceback (most recent call last):
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/commands/handler.py", line 373, in handle
    await handler(evt)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/commands/handler.py", line 289, in __call__
    return await self._handler(evt)
  File "/opt/matrix-bridges/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/commands/telegram/auth.py", line 128, in login
    url = f"{prefix}/login?token={evt.public_website.make_token(evt.sender.mxid, '/login')}"
AttributeError: 'NoneType' object has no attribute 'make_token'

what am i doing wrong? :(

kind regards, Mario

**Comment by tulir** [comment]
Oh right, that got into rc4. Should be already fixed in master by 7e3c892ff647f698b331a59b9cf3cca1097fa035.

**Comment by vmario89** [comment]
Hi,

i installed now directly from git master, but the error still occures:


Mär 18 04:59:56 h2606131.stratoserver.net mautrix-telegram.sh[12893]: [2019-03-18 04:59:56,977] [ERROR@mau.commands] Unhandled error while handling command login  from @matrixadmin:matr
Mär 18 04:59:56 h2606131.stratoserver.net mautrix-telegram.sh[12893]: Traceback (most recent call last):
Mär 18 04:59:56 h2606131.stratoserver.net mautrix-telegram.sh[12893]:   File "/opt/matrix-bridges/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/commands/handler.py", lin
Mär 18 04:59:56 h2606131.stratoserver.net mautrix-telegram.sh[12893]:     await handler(evt)
Mär 18 04:59:56 h2606131.stratoserver.net mautrix-telegram.sh[12893]:   File "/opt/matrix-bridges/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/commands/handler.py", lin
Mär 18 04:59:56 h2606131.stratoserver.net mautrix-telegram.sh[12893]:     return await self._handler(evt)
Mär 18 04:59:56 h2606131.stratoserver.net mautrix-telegram.sh[12893]:   File "/opt/matrix-bridges/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/commands/telegram/auth.py
Mär 18 04:59:56 h2606131.stratoserver.net mautrix-telegram.sh[12893]:     url = f"{prefix}/login?token={evt.public_website.make_token(evt.sender.mxid, '/login')}"
Mär 18 04:59:56 h2606131.stratoserver.net mautrix-telegram.sh[12893]: AttributeError: 'NoneType' object has no attribute 'make_token'

**Comment by tulir** [comment]
Are you sure you installed the latest version? I can't reproduce it anymore

**Comment by vmario89** [comment]
i killed everything and made it up again. now it works. please close this issue. regards
